- name: Create users
  user:
    name: "{{ user }}"
    password: "{{ password }}"
    shell: /bin/bash
    group: "{{ group }}"
    append: yes

- name: User is password-less sudoer
  template:
    src: 90-packer-init-users
    dest: /etc/sudoers.d/90-packer

- name: Allow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication no"
    line: "PasswordAuthentication yes"
  register: authentication_result
