#- name: Ports are open
#  iptables:
#    chain: INPUT
#    source: 0.0.0.0/0
#    destination: 0.0.0.0/0
#    protocol: tcp
#    destination_port: 80
#    match: state
#    ctstate: NEW
#    jump: ACCEPT

- name: Packages are present
  yum:
    name: haproxy
