- include: debian.yml
  when: deployment != 'Docker' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- include: yum.yml
  when: deployment != 'Docker' and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- include: docker.yml
  when: deployment == 'Docker'

- name: Home is present
  file:
    path: "{{ jenkins_home }}"
    mode: "0777"
    state: directory

- name: License is present
  copy:
    src: license.xml
    dest: "{{ jenkins_home }}/license.xml"
    mode: "0777"
  when: copy_license is defined
  register: license_result

- name: Configs are present
  copy:
    src: "{{ item }}"
    dest: "{{ jenkins_home }}/{{ item }}"
    mode: "0777"
  with_items:
    - config.xml
    - jobs
  register: config_result

- name: Service is running
  service:
    name: jenkins
    state: started
  register: service_result
  when: deployment != 'Docker' and not ignore_service_run is defined

- name: Service is restarted
  service:
    name: jenkins
    state: restarted
  when: deployment != 'Docker' and service_result is defined and (license_result|changed or config_result|changed) and not service_result|changed

- name: Containers are restarted
  command: docker-compose restart
  args:
    chdir: "/composes/cje"

- debug:
    msg: "CloudBees Jenkins Enterprise is running. Please open http://{{ ansible_hostname }}:8080"
  when: not ignore_service_run is defined
