- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Update Jenkins home
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_HOME=
    line: JENKINS_HOME="{{ jenkins_home }}"

- name: Update Jenkins port
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_PORT=
    line: JENKINS_PORT="{{ jenkins_port }}"

- name: Home is present
  file:
    path: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    mode: "0777"
    state: directory

- name: License is present
  copy:
    src: license.xml
    dest: "{{ jenkins_home }}/license.xml"
  when: copy_license is defined
  register: license_result

- name: Service is running
  service:
    name: jenkins
    state: started
  register: service_result
  when: not ignore_service_run is defined

- pause: seconds=6
  when: service_result|changed
  tags: [jenkins]

- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://localhost:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: "{{ jenkins_home }}/plugins/{{ item }}"
  with_items: "{{ plugins }}"
  register: plugins_result

- wait_for:
    path: "{{ jenkins_home }}/plugins/{{ item }}"
  with_items: "{{ plugins }}"

- name: Service is restarted
  service:
    name: jenkins
    state: restarted
  when: plugins_result|changed

- debug:
    msg: "CloudBees Jenkins Enterprise is running. Please open http://{{ ansible_hostname }}:8080"
  when: not ignore_service_run is defined
