#- name: Ports are open
#  iptables:
#    chain: INPUT
#    source: 0.0.0.0/0
#    destination: 0.0.0.0/0
#    protocol: tcp
#    destination_port: 8080
#    match: state
#    ctstate: NEW
#    jump: ACCEPT

- name: Package is downloaded
  get_url:
    url: http://nectar-downloads.cloudbees.com/nectar/rpm/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  register: repository_result

- name: Key is added
  rpm_key:
    key: http://nectar-downloads.cloudbees.com/nectar/rpm/cloudbees.com.key

- name: Package is installed
  yum:
    name: jenkins
    update_cache: yes
