- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Jenkins home is present
  file:
    path: "{{ cjoc_home }}"
    state: directory
    owner: jenkins-oc
    group: jenkins-oc
    mode: "0777"

- name: vagrant user is added to the jenkins-oc group
  user:
    name: vagrant
    group: jenkins-oc

- name: jgroups are present
  template:
    src: "{{ item }}"
    dest: "{{ cjoc_home }}/{{ item }}"
    owner: jenkins-oc
    group: jenkins-oc
  with_items: "{{ configs }}"
  when: install_result|changed

- name: Update Jenkins home
  lineinfile:
    dest: /etc/sysconfig/jenkins-oc
    regexp: ^JENKINS_HOME=
    line: JENKINS_HOME="{{ cjoc_home }}"

- name: License is present
  copy:
    src: license.xml
    dest: "{{ cjoc_home }}/license.xml"
  when: copy_license is defined
  register: license_result

- name: Service is running
  service:
    name: jenkins-oc
    state: started
  register: service_result

- name: Service is restarted
  service:
    name: jenkins
    state: restarted
  when: service_result is defined and license_result|changed and not service_result|changed

- debug:
    msg: "CloudBees Jenkins Operations Center is running. Please open http://{{ ansible_hostname }}:8888"
  when: not ignore_service_run is defined
