#- name: Ports are open
#  iptables:
#    chain: INPUT
#    source: 0.0.0.0/0
#    destination: 0.0.0.0/0
#    protocol: tcp
#    destination_port: "{{ item }}"
#    match: state
#    ctstate: NEW
#    jump: ACCEPT
#  with_items: ports

- name: Packages are present
  yum:
    name: net-tools

- name: Key is imported
  rpm_key:
    key: http://downloads.cloudbees.com/cjoc/latest/rpm/cloudbees.com.key

- name: Repository is added
  get_url:
    url: http://downloads.cloudbees.com/cjoc/latest/rpm/jenkins-oc.repo
    dest: /etc/yum.repos.d/jenkins-oc.repo

- name: Package is installed
  yum:
    name: jenkins-oc
    update_cache: yes
  register: install_result
