version: '2'

services:

  cje:
    container_name: cje
    image: cloudbees/jenkins-enterprise
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - $PWD/data/cje:/var/jenkins_home

  cjoc:
    container_name: cjoc
    image: cloudbees/jenkins-operations-center
    ports:
      - 8080:8080
      - 50000:50000
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/data/cjoc:/var/jenkins_home

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - $PWD/data/jenkins:/var/jenkins_home

  agent:
    container_name: jenkins_agent
    image: vfarcic/jenkins-swarm-agent
    environment:
      - COMMAND_OPTIONS=-master http://${MASTER_IP}:8080 -labels 'docker' -executors 5 -username admin -password admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
      - ${HOME}/.docker/machine/machines:/machines

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    image: kibana
    ports:
      - 5601:5601

  logstash:
    container_name: logstash
    image: vfarcic/logstash-jenkins-analytics
    volumes:
      - $PWD/data/docker.events:/docker.events
    ports:
      - 5678:5678
      - 31311:31311

  gitlab:
    container_name: gitlab
    image:
      gitlab/gitlab-ce
    ports:
      - 8080:80
    volumes:
      - $PWD/data/gitlab/config:/etc/gitlab
      - $PWD/data/gitlab/data:/var/opt/gitlab

  svn:
    container_name: svn
    image: erikxiv/subversion
    environment:
      - SVN_REPONAME=repos
    ports:
      - 3690:3690