version: '2'

services:

  cje:
    container_name: cje
    image: cloudbees/jenkins-enterprise
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /tmp/jenkins:/var/jenkins_home
#      - /data/jenkins:/var/jenkins_home
    restart: always
