- hosts: cje
  remote_user: vagrant
  serial: 1
  vars:
    - jenkins_home: /var/lib/jenkins/
    - jenkins_port: 8080
  roles:
    - common
    - { role: java, when: "deployment == 'package' }
    - { role: docker, when: "deployment == 'Docker' }
    - { role: docker-compose, when: "deployment == 'Docker' }
    - cje
